#!/usr/bin/env python

# translate: google translation from the commandline
# AO-2019
#
# INSTALL : pip install googletrans
#           pip install termcolor
#           cp translate ~/bin (or a location in your $PATH)
#           chmod u+x translate
#
# https://pypi.org/project/googletrans/
#
import sys
import os
from termcolor import colored
from googletrans import Translator

def read_in():
    lines=['']
    try: 
    	lines = sys.stdin.readlines()
    except KeyboardInterrupt:
	pass
    s = ""
    for i in range(len(lines)):
        s =  s + lines[i]
    return s

def main():
	argc = len(sys.argv)
	if argc == 1:
		print "translate \"Some text\" (or - for stdin)  <dest>"
		return
	langcodes = sys.argv[2:argc]
	if len(langcodes) == 0:
		langcodes=['nl']
	if sys.argv[1] == '-':
		lines = read_in()
	else:
		lines = sys.argv[1]
	translator = Translator()
	for langc in langcodes:
		try: 
			T = translator.translate(lines, dest=langc)
		except ValueError:
			print "?"
			continue
		if len(T.text):
			print colored(T.text, 'red')
		else:
			print "?"

				
if __name__ == "__main__":
	main()
	
